SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `page_columns`;
DROP TABLE IF EXISTS `pages`;
DROP TABLE IF EXISTS `documents`;
START TRANSACTION;
CREATE TABLE `documents` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`source_file` VARCHAR(255) NOT NULL,`source_path` TEXT NOT NULL,`created_at` VARCHAR(35) NOT NULL,`page_count` INT UNSIGNED NOT NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `pages` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`document_id` BIGINT UNSIGNED NOT NULL,`page_number` INT UNSIGNED NOT NULL,`text` LONGTEXT NOT NULL,`character_count` INT UNSIGNED NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY `document_page` (`document_id`,`page_number`),CONSTRAINT `pages_document_fk` FOREIGN KEY (`document_id`) REFERENCES `documents` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `documents` (`id`,`source_file`,`source_path`,`created_at`,`page_count`) VALUES (1,'azmyrat Şadurdyýew~Teke gyzy Tatýana (Artykgül) hakynda.pdf','/Users/macmini/Desktop/pdf-to-stories/input/azmyrat Şadurdyýew~Teke gyzy Tatýana (Artykgül) hakynda.pdf','2026-09-11T07:18:57Z',42);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (1,1,1,'',0);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (2,1,2,'ÝAZMYRAT ŞADURDYÝEW

TEKE GYZY TATÝANA (ARTYKGÜL) HAKYNDA

(gürrüňdeşlik)',73);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (3,1,3,'(Annagül eje bilen gürrüňdeşlik)

I Içi giň jaýyň edil ortarasynda, pessejik hem kiçiräk stoluň başynda biz Annagül eje bilen ikiçäk otyrys. 80 ýaşy arka atan bu ene saglygynyň gowşak bolmagyna garamazdan juda janly gürrüň berýär. Hereketlerem, birtüýsli, janly. Ol edil şu wagt gürlemezçe-de däldi. Çünki ol taryhymyzda wajyp bir waka barada gürrüň berýär. Annagül eje — Tatýana (Artykgül) Tekinskaýanyň gyzy — Annagül Myradowna Tekinskaýa. Merdana türkmen zenanynyň ýeketäk diri galan perzendi. Onuň agyr, dartgynly, emma manyly durmuşynyň kiçijik şaýady. Biz gürrüň edip oturyşymyza 3-4 ýaşlyja türkmen gyzjagazynyň elde çekilen suratlaryny synlaýardyk. Suratkeşiň çeken şol suratlaryny Annagül ejä görkezemizde, ol suratlaryň birini saýlap alyp: «Ine, şujagaz ejeme çalym edýär.Garagözelek, namysjaňja gyzjagaz. Gözlerem, gaşlaram edil ejemiňkä çalym edýär…» diýdi. Şeýdip, 5-6 suratdan ýekejesini saýlap aldyk. Dogrudanam, şol saýlanan surat üýtgeşikdi. Ondaky gyzjagazyň gözlerinde üýtgeşik many bardy.

3',1011);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (4,1,4,'Tatýana Tekinskaýanyň çagalygyny ýatlajak bolup, oňa kän seredip oturdym. Ine, birdenem şol suratdaky teke gyzjagazy bilen hyýalymda gürleşenimem duýman galypdyryn. Bu näbelli gyzjagazdan men soraýaryn, olam jogap berýär: «Sen kim, gyzjagaz?» «Bilemok...» «Seň adyň näme?» «Bilemok...» «Adyňam bileňokmy?» «Ýok...» «Kimiň gyzy? Ejeň-kakaň kim?» «Bilemok... Men hiç zat bilemog-a...» «Nirede ýaşadyň sen?» «Hanha, ho-o taýda...» «Kimler diýýärdiler size?» «Tekeler...» «Kimler?» «Tekeler biz… Düşüneňokmy, te-ke-ler...» «Sen onda teke gyzy-da, şeýle dälmi?»

4',559);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (5,1,5,'«Hawa, teke gyzy...» Häli-häzire çenli Tatýana Tekinskaýanyň hakyky ady, atasynyň ady belli däl. Gaty kiçijik bolansoň ol adynam bilmändir. Dogrusy, düşündirip bilmändir hiç kime. Şol teke gyzlygyna-da galypdyr. Elbetde, ady bolandyr o görgülijigiňem. Atasam bolandyr, enesem. Doganjyklaram bolandyr, kim bilýär. Günde onuň adyny tutup gygyrandyr ejesi. «Guzym, balam» diýendir. Söýendir, hüwdiländir. Ak göwsünden süýt berendir. Emma, zalym ykbal o görgülijigi hemme zatdan mahrum etdi oturyberdi. Hatda öz adynam biler ýaly etmedi. Atsyzja teke gyzy bolup galdy, görgülijik. Men hyýaly pikirden çykyp bilmän ýene-de teke gyzjagazynyň çagalygyny göz öňüme getirjek boldum: beýikli-pesli gum depelerinde 3-4 ýaşlyja gyzjagaz ylgap ýör. Ol ylgap barşyna hezil edip gülýär. Neneň gülmesin — asman arassa, zemin arassa. Gün ýyly mähri bilen çoýup dur. Daş-töwerek ümsümlik. Asudalyk. Gyzjagaz aýak ýalaňaç ylgap ýörşüne hezil edýär. Onuň elinden-aýagyndan saklaýan ýok — erkin! Ine, birdenem dünýäni apy-tupan tutýar. Elhenç gümmürdi ýeri sarsdyryp, asmany gara buluda örtýär. Gyzjagazyň şadyýanja gülkisiniň üstüni ahy-nala basýar. Edil zeminiň teýinden çykýan ýaly adamlaryň, çagalaryň

5',1187);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (6,1,6,'aglap-eňreýän, ýürek sarsdyryjy sesleri eşidilýär. Bu Gökdepe urşunyň ýaňy. Elhenç gyrgynçylygyň ýaňy. Adam mertebesiniň düýp teýkary bilen basgylanan gününiň ýaňy. Edil şol wagt meniň bir döwür syn eden suratlarym ýadyma düşdi. Ine, şol gandöküşikli urşy beýan edýän fransuz hudožnigi Ef Rubonyň «Gökdepe galasynyň zabt edilişi» suraty… Partladylan galanyň içine rus goşunlary süsdürilip girýärler. Olar hiç kimi aýanoklar — çagamy, garrymy, tapawudy ýok — hemmesini gyrmaly. Ine, şol ahyrzamany sypatlandyrýan suratyň içinde bizi aýratyn bir sahna özüne çekýär. Ýaşy bir çene baran garryja türkmen enesi kiçijik çagany bagryna basyp, duşmanyň gözünden sypjak bolýar. Bu görgüli garrynyň edil şu wagt bar aladasy şol çagany halas etmek. Neslini halas etmek. Nesil daragtyny dowam etdirmek. Ine-de, näbelli rus hudožniginiň Gökdepe galasy zabt edilenden soň çeken suraty. Weýran bolan galanyň içinden general Skobelew öz atlylary bilen çykyp gelýär. Edil galanyň düýbünde, Skobelewiň gelýän ugrunda, bir kiçijik teke gyzy eginjigini gysyp otyr. Ol görgülijik bar zatdan bizar bolupdyr. Daş-töwerekdäki bolup geçýän elhençliklere akyl ýetirip bilmän, gözlerini tegeläp otyr...

6',1178);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (7,1,7,'1882-nji ýylda Gökdepe urşuna gatnaşan Maslowyň Sankt-Peterburgda çapdan çykan, «Ahal-Tekäniň zabt edilişi» atly kitabyndan: «Galadan çykyp gelýän Skobelewiň atynyň öňüne duýdansyz bir ýerden bir gyzjagaz okduryldy. Skobelew şo bada atyny saklap, gyzjagazy ýygnamagy soldatlardan haýyş etdi. Ol gyzjagazy öz bolýan lagerine äkitmeklerini buýurdy. Soň Skobelew tapylan teke gyzyny grafinýa Milýutina tabşyryp, oňa esewan bolmagyny haýyş etdi. Bu teke gyzyndan örän üýtgeşik adam boljakdygyna onuň ynamy bardygyny grafinýa ýaňzytdy. Dogrudanam, galadan tapylan gyzjagaz gaty üýtgeşikdi. «Tatýananyň gününde» galadan tapylansoň ol gyzjagaza «Tanýa» diýip at goýdular. Oňa täze eşik geýdirenlerinde bolsa ol şeýle bir owadanja we şadyýanja boldy. Üç aý geçenden soň rus dilinde şeýle bir oňat geplemegi öwrendi welin, onuň dil bilşi rus çagalarynyňkydan pes däldi. Ol daşyndan garaýagyz hem janlyja diýäýmeseň rus çagasyndan tapawutlandyrjak gümanyň ýokdy... Başga-da galadan kän çaga tapyldy. Olaryň köpüsi oglanjyklardy. Ofiserlerimiz olary ýanlarynda saklaýardylar. Garaz, her rotada birlänikilän çaga bardy. Ulular olary oýnadýardylar...». Annagül ejäniň ýygyrt atan horja ýüzüne seredip

7',1190);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (8,1,8,'oturyşyma onuň gürrüňini diňleýärin: « — Gökdepe galasy basylyp alnanda meň ejemiň 3 ýaşy dolan ekeni. Şol apy-tupanda bir gudrat bilen diri galypdyr. Galadan çykyp, harabalykda aýlanyp ýörkäde, general Skobelew atdanlykda onuň üstünden barýar. Soldatlara bu gyzjagazy ýygnamagy buýrupdyr. Şeýdip meň ejem ruslaryň eline düşýär. Başda ony meýdan keselhanasyna eltýärler. Şol ýeriň denşigi, rus soldaty Rodiony gyzjagaza eneke edip belleýärler…». 1882-nji ýylda Sankt-Peterburgda çapdan çykan «Rodnik» atly çagalar žurnalynda Ahal-Teke urşuna gatnaşan harby lukman A.W. Şerbagyň «Teke gyzjagazynyň hem-de onuň soldat enekesi Rodionyň taryhy…» atly oçerkinde şeýle täsirli setirler bar: «...Gyzjagaza eneke bolmak Rodiona diýseň ýarady. Ol ilki bilen gyzjagazy ýyljak suwda ýuwundyrdy. Kiçijik çaga suwa düşmek gaty bir ýaramansoň, çirkin ses edip aglamaga başlady. Diýen etmän elini-aýagyny ikiýana urdy. Rodion bolsa çagaň gykylygyna bakman, ony derrew suwa düşürdi. Soňam soldatlaryň eşiginden tikilen köýnejigi geýdirdi, ony ýaglyga dolady, aýagyna bolsa köwşüň deregine ýüň jorap geýdirdi. Soňam gyzjagazy ýaralylary ýatyrylýan galtagyň üstünde

8',1150);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (9,1,9,'ýatyryp, gyzgynja çaý berdi. Şol günüň agyr jebirlerini başdan geçiren gyzjagaz şol bada süýji uka gitdi... ...Bu gyz Tanýa Tekinskaýady. Ol diňe Rodion bilen grafinýa Milýutina öwrenişipdi. Başga hiç kimi gyzjagaz golaýyna eltenokdy. Ol hemişe Rodionyň yzyna düşüp ýörendir. Ol kä wagtlar soldata türkmençe-de bir zatlary diýip goýberýärdi. Ine, şonda Radion hiç zada düşünip bilmän gyzjagaza gözlerini tegeläp seredýärdi. Gyzjagaz bolsa enekesiniň bu gülkünç halyna heziller edip gülýärdi». Annagül eje suratlara göz gezdirip gürrüň berýär: «Gökdepe urşuna gatnaşanlaryň käbirleri kitapdyr žurnallarda ejem barada-da agzap geçipdirler. Ýöne, bize ejem öz ýaşlygyny özi gürrüň berýärdi. Oňa at dakylyşam gaty geň bolupdyr. Şol wagt näsaglara esewan bolýan grafinýa Ýelena Dmitriýewna Şahowskaýa-Milýutina ejeme eýe çykypdyr. Ol şol wagtky Russiýanyň harby ministri Milýutiniň gyzy ekeni. Grafinýa ejemiň adyny bilip bilmänsoň özüçe at goýypdyr. Gökdepe galasy ýanwar aýynyň 12-sinde basylyp alnypdyr. Ol gün ruslaryň «Tatýananyň güni» atly dini baýramçylygy ekeni. Şonuň üçin ejeme «Tatýana» diýip, at goýupdyrlar. Tatýana ähli «Tatýana» atly gyzlaryň perişdesi ekeni. Soň «Mihaýlowna» diýip

9',1195);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (10,1,10,'at goýupdyrlar. Ejemi ilki bilen ýygnan Mihail Skobelew bolansoň ony ejemiň atalygy hasaplapdyrlar. Ejem teke gyzy bolansoňam oňa «Tekinskaýa» diýip familiýa goýupdyrlar. Şeýdibem ejem Tatýana Mihaýlowna Tekinskaýa bolaýypdyr...» Teke gyzy barada gürrüň berýän «Rodnik» çagalar žurnalyndaky oçerke ýene bir gezek göz gezdirýäris. Teke gyzjagazy baradaky setirlerden gözüňi aýyrmak mümkin däl: «...Gami ýuwaş-ýuwaşdan açyk deňze girip başlady. Kenar hol yzda galdy. Adamlaryň gowry ýatyşdy. Tanýa-da gürlemesini bes etdi. Oturgyçda gysylyp oturyşyna tolkun atýan deňze, hol uzakda galan kenara gaýgyly gözjagazlaryny aýlady. Soňam ýuwaşjadan uka gitdi… Gämiň bir çetinde bolsa rus soldaty egnini gysyp otyrdy. Ol gaýgylydy. Olam uzakda galan kenara seredip, gözlerine ýaş aýlady. Ol — Rodiondy... Tanýany onuň elinden aldylar. Gyzjagazy Moskwa äkidip okuwa ýerleşdirmegi makul bildiler. Tanýa özüniň täze durmuşyna begenjeginem-gynanjagynam bilmedi. Rodion bolsa aglaýardy. Çünki ol Tanýa bilen ömürlik aýralykda galmaly bolupdy... Bir aý geçenden soň Tanýany Moskwada hristian dinine kabul etdiler. Soňam ojagaz gyzjagazy döwletiň hasabyna «Nikolaýewskiý»

10',1159);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (11,1,11,'ýetimler öýüne tabşyrdylar...» Ine, şeýle... Çaklaňja oçerkde gör, näçe maglumat ýatyr. Teke gyzjagazy özüniň üýtgeşik häsiýetleri bilen köpleriň ünsini çekipdir. Emma özi baradaky ýazgylardan bolsa onuň habary bolmandyr. Diňe ulalyp ýetişensoň, ol şol ýazgylar bilen tanyş bolupdyr. Ine, şonda oňa köp zat aýan bolupdyr. Taryhda gör, nähili wakalar, ykballar ýatyr... Eýýamlar diýseň çalt üýtgäpdir. Adamzadyň taryhynda dürli öwrülişikler bolup geçipdir. Patyşa Russiýasynda XIX asyryň ahyrynda iň bir wajyp wakalaryň biri, olam ruslaryň Gökdepe urşundaky ýeňşi bolupdyr. Bu ýeňiş Russiýanyň basybalyjylykly syýasatynda uly öňegidişlige ýardam edipdir. Şol döwrüň harby ministri Dmitriý Alekseýewiç Milýutin öz «Gündeliginde» şeýle bellik edýär: «Skobelewiň ajaýyp ýeňşi bütin Ýewropada uly täsir galdyrdy. Onsaňam ol ýeňiş iňlisleriň başda Owganystanda, soňam Günorta Afrikadaky şowsuzlyklary bilen gabat geldi. Bu bolsa biziň üçin gaty bähbitli boldy». Gökdepe urşy barada şol ýyllar Sankt-Peterburgda, Moskwada tom-tom kitaplar ýazyldy. Olaryň awtorlary bolsa Gökdepe urşuna gatnaşyp, ähli zatlary öz gözleri bilen gören adamlardy — Grodekow, Maslow, Şerbak, Terentýew, Kuropatkin… Wereşagin ýaly hudožnikler Gökdepe

11',1224);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (12,1,12,'hakykatyny görkezýän ençeme iniňi tikenekledýän eserleri döretdi. Hatda «Gökdepe» atly harby marş hem düzülipdir...

II Uruşda gyrlan adamlaryň, alnan oljalaryň ýörite hasaby ýöredilipdir. Egsilmez rus goşunynyň, general Skobelewiň ady arşa göterilip şöhratlandyrylýar. Gökdepe urşunda gazanan ýeňşi üçin general Skobelew «Swýatoý Georgiý» Hajy bilen sylaglanylýar. Generallykdan general-adýutantlyga çekilýär. Ol hakyky halk gahrymanyna öwrülýär. Ýöne esasy ýeňiş ruslar üçin başga zatdy. XVIII asyrda Pýotr I-iň amala aşyrmaga hyýallanan maksady XIX asyryň ahyrynda ýol alyp ugraýar. Ol maksat — basybalyjylyk maksady. Özge ýurtlary basyp alyp, özüne tabyn etmek, boýun egdirmek syýasaty. Pýotr I öz döwründe Orta Aziýanyň üsti bilen Hindistana ýetmek, ony boýun etmek maksady bar ekeni. Emma, onuň ilkinji synanyşygy şowsuz gutarýar. Hywa iberen Bekowiç-Çerkasskiniň ýolbaşçylygyndaky ekspedisiýasy derbi-dagyn edilýär. XIX asyryň ikinji ýarymynda bu wajyp işiň täzeden ugruna çykylýar. «Slawýan doganlarymyz howp

12',1020);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (13,1,13,'astynda» bahanasy bilen ruslar Bolgariýany «azat» etmek maksady bilen Türkiýä uruş yglan edýärler. Çünki Bosfor hem Dardanelli aýlaglarynyň üsti bilen Owganystana, soňam Hindistana aşyp bolýardy. Emma rus-türk urşy gaty agyr bolansoň, Russiýanyň goşuny sandan çykýar. Ummasyz köp serişde harç edilýär. Bosfor aýlagynyň üsti bilen Hindistana geçmek plany başa barmaýar. Şonuň üçin ruslar ýeňilräk hem ýakyn ýol agtarýarlar. Ýeke-täk ýol — olam Orta Aziýanyň üsti bilen aşmak bolýar. Ine, şonuň üçin 1878-nji ýylda general Lomakiniň ýolbaşçylygyndaky rus goşunlary Orta Aziýa hüjüm edýärler. Bu ýörüş hem ruslar üçin şowsuz gutarýar… 1880-nji ýylda general Skobelewiň ýolbaşçylygyndaky goşun Kaspi deňziniň kenarynda, Çekişlerde düşleýär. Harby-tehniki enjamlary, ýaraglary üpjün bolan ägirt uly goşun ýenede Orta Aziýa dökülýär. «Ak general» ady bilen belli Skobelew ozal Kawkazda, Hywada, Kokantda, rus-türk uruşlarynda özüniň ganhorlygy bilen tapawutlanan adam. Russiýanyň bähbidi üçin ol hiç zatdanam gaýdanokdy. Başga halklara garşy onuň öz syýasaty bardy. Ol şeýle ýazýar: «Aziýanyň diňe bir emlägini däl, onuň aňyny hem almak gerek». Onuň ildeşi we kärdeşi general Maslow bolsa Skobelewiň aýdanlarynyň

13',1210);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (14,1,14,'üstüni ýetirýär: «Bary-ýogy on aýyň içinde Skobelew Ahal-Teke ekspedisiýasyny üstünlikli tamamlap, Orta Aziýada rus agalygyny berkitdi…». Gökdepe urşuna gatnaşyp, tekeleriň gahrymançylyklaryny, olaryň ýanbermezliklerini öz gözleri bilen gören general Grodekow bolsa: «Türkmenler — Ýer şarynyň ýüzünde dörän tegmil. Olar adamzady masgara edýär. Şonuň üçin olardan dynmaly» diýip, haýbat atýar… Gökdepe urşundan has soň, ömrüni Patyşa Russiýasynyň harby bölümlerinde gulluk eden, rustürk, Kawkaz uruşlaryna gatnaşan harby ýurist, polkownik, Çekişlerde doglan Nikolaý han Ýomudskiý öz ýatlamalarynda şeýle ýazýar: «Türkmenler müň ýyllyklaryň dowamynda Aziýanyň sähralyklarynda erkin ýaşap ýören halk. Olar öz üstlerinden agalyk edýän häkimligi, erkinligini elinden alýan kanunlary görmedik halk. Türkmenleriň bütin ömri erkinlikde geçen, olaryň bütin daş-töweregini erkinlik gurşap alan, şonuň üçin olara agalyk ediji güýç täsir etmeýär». Ol öz ýatlamasynda başga bir pikiri hem orta atýar: «Baryp has irki döwürlerden rus patyşalarynda özge halklaryň ýerini, ýurtlaryny basyp almak endikleri bardy. Olar günbatarda-da, gündogarda-da häli şindi basybalyjylykly ýörüşleri

14',1171);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (15,1,15,'guraýardylar. Halkary gulçulyga öwürýärdiler. Özleriniň basybalyjylykly hereketlerini bolsa olar ynsansöýüjilik pikirleri bilen ýumarlaýardylar...». Hawa, 1881-nji ýyl Rus patyşasy üçin bähbitli ýyl boldy. Bütin Orta Aziýa eýelendi. Indi beýleki maksatlaryňam amala aşyrybermeli. Hindistan, Owganystan, beýleki gündogar ýurtlaram indi uzakda däl. Olara tarap ymykly ýol açyldy. Emma, 1882-nji ýylyň awgust aýynyň 25-inde garaşylmadyk bir waka boldy. General Skobelew Moskwanyň kaşaň myhmanhanalarynyň birinde keýp çekýän mahaly ölýär. Gökdepe urşunda rehimsiz gyrgynçylyga ýol beren, öwezini dolduryp bolmajak ýitgileriň döremegine sebäp bolan «gözi ganly» general amanadyny tabşyrýar… Skobelewiň ölümini bütin Russiýa gynanç bilen kabul edýär. Ähli gazetdir-žurnallar generalyň ölümine matam tutmak bilen gynanç bildirýärler. «Nowoýe wremýa» žurnaly bolsa şeýle ýazýar: «Şugla saçýan ägirt meteor daşy ýaly ol — Skobelew, dünýäniň üstünden aýlanyp, ömürlik gözden ýitdi…». Patyşa Russiýasynda bolup geçýän bu galagoply wakalardan dört ýaşynda Russiýa äkidilen, Gökdepe urşunda ene-atasyndan jyda düşen teke gyzjagazynyň, general Skobelewiň gyzlygy hasap edilýän mährem gyzjagazyň habary ýokdy. Ol bu wagt

15',1209);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (16,1,16,'düýbinden üýtgeşik ýurtdaky, Russiýadaky durmuşyna ymykly öwrenişipdi... Käbir derejede teke gyzynyň ykbaly bilen baglanyşykly taryhyň sahypalaryna ser salyp, ýene-de Annagül ejäniň otagyna dolanyp gelenimizi duýman galdyk. Ol görgüli bolsa şol gürrüň berip otyr. Ejesi hakynda onuň gursagynda juda-juda gürrüň köpdi... « — Ejemiň Russiýada 5-6 ýaşyndaky aldyran suraty bardy. Rus dworýan çagalarynyň eşiginde. Başynda owadanja şlýapajygy bar, egninde üýtgeşik köýnejigi. Şeýle bir gowuja, akylyňy haýran eder. Ejemiň çagalygyndan galan ýeke-täk şol suratdy. Emma, ýadyma düşenok, kimdir biri alyp, soň gaýtaryp getirmedi. Şonda ol ýetimler öýünde terbiýelenýär ekeni. Ejem akyllyja hem dogumlyja bolansoň derrew özüni aldyrypdyr. Oňa hemmeleriň göwni ýetipdir. Ejemiň çagalygyna degişli hiç bir zat galmandyr. Moskwanyň arhiwlerinde käbir maglumatlar bolmagy ahmal. Ýöne kim ony barlajak, öwrenjek. Soň ejem ýetişensoň Ýelizawetanyň adyny göterýän zenanlar institutyna kabul edýärler. Ol institutda diňe dworýanlaryň, ýokary çinli harby adamlaryň, täjirleriň garaz ýokary gatlagyň çagalary okaýardylar. Ejem instituty 1894-nji ýylda tapawutlanan bahalar bilen gutarýar...»

16',1177);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (17,1,17,'Türkmenistanyň merkezi döwlet arhiwinde Tatýana Tekinskaýanyň terjimehalyna degişli ýörite bukja bar. Ine, şonuň içinde bolsa Tekinskaýanyň durmuşy hakynda gymmatly maglumatlar ýerleşdirilipdir. Ynha meniň elimde Tatýana Tekinskaýanyň instituty tamamlanlygy baradaky «Şahadatnamasy». Saralyp giden galyň kagyzyň ýüzünde şeýle ýazgylar bar: «… Moskwanyň Ýelizaweta institutynda terbiýe alan, general-adýutant M. D. Skobelewiň hem-de knýaginýa E. D. Şahowskaýanyň gyzlygy hasap edilýän Tatýana Mihaýlowna Tekinskaýa şu okuw jaýynda okaýan döwründe ahlakdan «bäşlik», Allatagala kanunlaryndan «bäşlik», rus dilinden we sözleýşinden «gaty oňat», fransuz dilinden hem sözleýşinden «gaty oňat», nemes dilinden we sözleýşinden «oňat», matematikadan «bäşlik», geografiýadan «gaty oňat», taryhdan «has oňat», pedagogikadan «bäşlik» bahalara mynasyp boldy. Bulardan başga-da Tekinskaýa okuw döwründe surat çekmek, ýazmak, saz we tans, el işleri, hojalyk işleri boýunça tälim alyp, instituty tamamlandan soň «Ýazgyly kitaba» mynasyp boldy. Moskwa, 1894-nji ýylyň maý aýynyň 21-i…» «Şahadatnamanyň» gapdaly bilen birnäçe suratlara-da göz gezdirýärin. Tatýana Tekinskaýanyň Ýelizaweta zenanlar institutynda okan

17',1202);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (18,1,18,'döwründe aldyran suratlary… Onuň ýeke özüniň düşen suraty täsirli. Ine, gözleri ýanyp duran 17-18 ýaşlaryndaky gara gözelek teke gyzy. Onuň gözlerinde nähili hem bolsa gaýgy bar. Ine, beýleki suratda bolsa Tatýana Tekinskaýa öz bile okaýan joralary bilen surata düşüpdir. Özüniň owadanlygy bilen ol beýlekilerden saýlanyp dur… Tatýana Tekinskaýanyň okan Ýelizaweta institutynyň jaýy häzirem Moskwada bar. Jaýyň içinde köp özgerişlikler bolanam bolsa, onuň daşky keşbi känbir üýtgemändir. Üýtgeşik arhitekturasy bolan bu okuw jaýynyň kiçiräjik howlusy bar. Ortada uly fontan. Howlyň haýatam şol öňki salnylyşy ýaly dur. Ýelizawetanyň adyny göterýän zenanlar instituty öz döwründe juda meşhur bolupdyr. Bu ýerde hat-da meşhur şahyr A. S. Puşkiniň aýaly Natalýa Gonçarowa-da okapdyr. Ol barada bize bu ýeriniň taryh muzeýiniň işgäri, gartaşan zenan gürrüň berdi. Ol bize jaýyň içindäki demir basgançagy görkezip: «Ine, şu ýerde, bu basgançakda A.S. Puşkin Natalýa Gonçarowa bilen duşuşypdyram» diýýär. Bu mährem aýal Tekinskaýa barada-da, onuň şu ýerde okanlygy barada hem bilýän ekeni. Onuň uzak Orta Aziýadan getirilenliginden hem habary bar ekeni… Moskwada bolamda şol demir basgançaklara uzak

18',1197);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (19,1,19,'wagtlap seredip durdum. Teke gyzynyň ýöräp barşyny göz öňüme getirdim. Şol ýöräp barşynda-da, görgüli, kim bilýär, pikir edendir: «Kim men? Nirde meniň Watanym? Görermikäm heý dogduk mekany?…» Ol mümkin ynha şu penjireden seredendir, synlandyr rus şäheriniň adamlaryny. Birdenem öz watandaşlary ýadyna düşendir... Gamgynlanandyr... Şu döwre çenli Tatýana Tekinskaýanyň okan okuw jaýy ençeme gezek üýtgäpdir. Ýelizawetanyň adyny göterýän institutdan soň, sowet döwri, ol Krupskaýa adyndaky pedagogik institut bolupdyr. Beýik Watançylyk urşy ýyllary bu jaý harby gospital bolupdyr. Soň «Kommunistik Pedagogik uniwersiteti» bolupdyr. Häzir bolsa bu jaýda Orsýediň Pedagogik instituty ýerleşýär… Men Annagül eje bilen ikiçäk oturyşyma oňa gyzyklanýan soraglarymy berýärin. Olam howlukman, her bir sözi ölçerip jogap berýär. Meni Tatýana Tekinskaýanyň institutdan soňky ykbaly gyzyklandyrýardy. « — Instituty tamamlandan soň ejemiň kyn güni başlanýar. Okuwy gutaryp, Moskwada öz okan institutynda işe galypdyr diýlen maglumatlar hem bar. Ýöne ol görgüli birbada özüni nirä urjagyny bilmändir. Özüniň türkmenlerdendigini, teke gyzydygyny oňa ozal köp ýatladypdyrlar. Özüniň keç ykbalyndan onuň

19',1191);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (20,1,20,'habary bar ekeni. Ýöne, Türkmenistana nädip aşmaly? Ony ol ýerde nähili kabul ederler? Kim garaşýarka oňa Türkmenistanda? Ol hakyky öz adynam, atasynyňejesiniň atlarynam bilenok ahyryn. Ol ýekeje zady bilýär — Gökdepeden, özem teke gyzy, başga hiç zat. Onsoň o görgülini şu ýagdaýda kim tanar? Onsoňam ol bütin tebugaty bilen rus durmuşyna, rus terbiýesine, däpdessuryna uýgunlaşan. Özem bütinleý rusça geýinýär. Öz türkmen dilini bilenok. Onuň türkmendigine beri ynanarlarmyka? Ine, şu çykgynsyz agyr ýagdaýlar ejemi kyn güne goýýar. Ýöne nähili kynam bolsa, özüniň esasy watany, türkmen topragy onuň kellesinden çykmaýar…»

III Men arhiwde maglumat toplan wagtlarym ýene bir üýtgeşik maglumatyň üstünden bardym. Ol Tatýana Tekinskaýa bilen Pýotr Skworsowyň nikalary barada güwä geçýän «Şahadatnama». Bir bölejik saralyp giden kagyzyň ýüzünde şeýle ýazgylar bardy: «Generaladýutant M. D. Skobelewiň we E. D. Şahowskaýanyň gyzlygy Tatýana Mihaýlowna Tekinskaýa bilen inženermehanik Pýotr Sergeýewiç Skworsew Moskwanyň

20',1021);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (21,1,21,'Ýelizaweta institutynyň ýanyndaky Troiskiý buthanasynda 1898-nji ýylyň awgust aýynyň 23-ine nikalaşdylar. Ruhany Dmitriý…» Bir bölek kagyzyň ýüzünde ynsan ykbaly ýatyr. Maşgala durmuşynda bolan ilkinji ädim ýatyr. Okuwy tamamlandan soň dört ýyl geçenden soň Tatýana Tekinskaýa durmuşa çykmagy makul bilýär. Ýekelik görgülini irizendirdä. Pýotr Skworsew diýen ýigide durmuşa çykýar. Ol ýigit Kuznetsow diýilýän täjiriň farfor zawodynda inžener bolup işleýän ekeni. Ýaşlar biri-birini halaşyp barypdyrlarmy ýa-da tötänlikde nikalaşypdyrlarmy — ol barada hiç hili maglumat ýok. Troiskiý buthanasyndada bolup gördüm. Ol Moskwanyň çeträginde ekeni. Içi üýtgeşik bezelen bu buthana häzirem öz görküni ýitirmändir. Ähli ýerden Isa pygamberiň suraty saňa seredip dur. Ine, şu ýerde, şu buthanada 100 ýyl töweregi mundan ozal teke gyzy ömründe ilkinji gezek nikalaşypdyr. Nähili duýgyny başdan geçirdikä şonda Tatýana Tekinskaýa? Elbetde, tolgunandyr… Annagül ejäniň gürrüňi meni uzak ýatlamalardan häzirki hakyky durmuşymyza alyp gelýär: «Ejem durmuşa çykandan soň, birnäçe ýyl Moskwada ýaşaýarlar. Soň Pýotr Skworsowy Harkowa işe geçirýärler. Harkowda farfor zawodynyň filialy

21',1173);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (22,1,22,'bar ekeni. Olar ol ýerde 1905-nji ýyla çenli ýaşaýarlar. Tatýananyň üç sany gyzy bolýar. Harkowda Tatýana Tekinskaýa ýerli gimnaziýada daşary ýurt dilleri boýunça okadýar. Durmuş öz ugruna gidip dur. Emma maşgalada oňşuksyzlyk başlanýar. Bar bela Pýotrdan gaýdýar. Ol içegen bolup, häli-şindi Tatýana azar berip başlaýar. Onuň üstesine-de Russiýada rewolýusion hereketler başlaýar. Uruş-sögüşler köpelýär. Kyn ýagdaýa düşen Tatýana öz Watanyna, Türkmenistana gaýdarman bolýar. Emma Pýotr Skoworsow garşy çykýar. Tekinskaýa uzak, näbelli Türkmenistana çagalaryny hem alyp gider öýdüp, ony öz çagalaryndanam mahrum edýärler. Üç sany garagözelek gyz Pýotr Skworsowda galynmaly edilýär. Şeýdibem ejem öz dogduk mekanyna ýeke özi gaýtmaly bolýar…» Tatýana Tekinskaýanyň özdiýenliligini subut edýän üýtgeşik maglumat bar. Onda Tekinskaýanyň Onuň Alyhezretleri imperatoryň kanselýariýa işleri boýunça Uprawlýaýuşisiniň adyna ýazan haýyşnamasy beýan edilipdir. Tatýana Tekinskaýa «Skworsowa» familiýasyny üýtgedip, öz «Tekinskaýa» familiýasyny gaýtaryp bermeklerini haýyş edýär. Onuň haýyşy kanagatlandyrylýar — «Tekinskaýa» familiýasy gaýtarylyp berilýär… Ol haýal etmän Türkmenistana

22',1181);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (23,1,23,'ugraýar. 25 ýyldan soň Tatýana Tekinskaýa dogduk mekanyna dolanyp gelýär. Türkmen topragy XX asyryň başynda… Men şol döwre degişli arhiw suratlaryna göz gezdirýärin. Ähli ýerde harby eşikli adamlar. Patyşa Russiýasynyň generallary, ofiserleri, soldatlary. Türkmen topragy ýetişibildiginden özgerdilýär. Demirýol gurulýar. Amyderýanyň üstünden köpri gurulýar. Jaýlar, ýollar, meýdançalar gurulýar. Buthanalar gurulýar. «Türkmenowedeniýe» žurnalynyň XX asyryň 20nji ýyllarynda çykan sanlarynyň birinde Nikolaý Han Ýomudskiý şeýle ýazýar: «40 ýyllap patyşa Russiýasynyň harby häkimligi Zakaspi oblastynda öz syýasatyny ýöretmek bilen türkmenleriň durmuşyna bitmejek ýara saldy: ýaşy könelişen garry-gurtylar-a öňki erkin durmuşy ýada salyp, öz içki dünýäleri bilen boluberdiler, soňky — täze nesil bolsa täze döwrüň ýagdaýyna görä boluberdiler. Daşyndan seretseň hemme zady boýun alyk, özgäň agalygyna tabyn halk, içinden şol agalyga närazylyk bildirýärdi. Olar özleriniň öňki erkin durmuşynyň täze tertip-düzgünler, kanunlar bilen boglup ýörenine gyýylýardylar, şeýdibem seslerini çykarman, ähli ahwalatlary öz içlerinde saklap, «Ak patyşanyň»

23',1145);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (24,1,24,'güýjüne bialaç boýun bolmaly bolýardylar…» Rus patyşasy Orta Aziýany basyp alanyndan soň bu toprakda diňe öz hökmüni ýöredýärdi. Diňe şolaryň döreden kanuny, düzgün-tertibi, däp-dessury, syýasaty amala aşyrylýardy. Şol kanunlara boýun bolunmadyk halynda kim bolsaň şol bol, derrew ugruňa çykylyp duşman hökmünde ýok edilýärdi. Tersine, Rus patyşasyna wepaly hyzmat etseň, başlaryna täç edip, sylag-serpaý berýärdiler. Tekinskaýa bu pajygaly ahwalata öz Watanyna gelen gününden göz ýetirýär. Erkinligini aldyran halkynyň çykgynsyz ýagdaýyna gynanýar. Ýogsam ol — Tatýana Tekinskaýa, erkinligi küýsäp öz dogduk mekanyna gelipdi ahyryn. Emma, hemme zat tersine bolup çykdy. Onuň 3-4 ýaşyndaky keç ykbaly ony ýetişip, 25-26 ýaşyndaky akylly-başly adam halynda-da öz penjesinden sypdyrmady… Annagül eje könelişen surat albomyna seredip oturyşyna suratlara göz gezdirýär. Tatýana Tekinskaýanyň suratlaryna… « — Ejem 1906-njy ýylda Aşgabada gelýär. Derrewem Daşkende ugraýar. Sebäbi, Aşgabatda işlemek üçin Daşkentden rugsat almalydy. Ejeme rugsat berensoňlar ol Aşgabada gelip, Zakaspiý oblast

24',1091);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (25,1,25,'kanselýariýasynda dilmaç bolup işleýär. Daşyndanam zenanlar gimnaziýasynda nemes, fransuz dilleri boýunça sapak berýär. Şol gimnaziýanyň jaýy häzir hem bar. Ol Mekan köşgüniň ýanyndaky öňki Medeni aňbilim tehnikumynyň ýeri. By gimnaziýada diňe ýokary gatlagyň çagalary okadylypdyr. Ejem bu gimnaziýa türkmen gyzlarynam çekjek bolýar, emma rugsat berilmeýär. Ejemiň erkin hereketleri şobada patyşa çinownikleriniň gözüne kaklyşýar. Bu akylly-başly, düşünjeli aýaldan az gorkmaýardylar…» Öz Watanyna sag-aman gelen Tatýana Tekinskaýa biraz wagtyň içinde esasy bir zada anyk göz ýetiripdi. Herhal erki elinden alnan, hiç bir zada hukugy ýok halkynyň agyr gününi nähili hem bolsa ýeňletmelidi. Ýöne ol döwürde bu ýeňil bolmadyk wajyp işi nähili amala aşyrmaly? Diňe bilim bermeli! Hawa-hawa, halky aňly-düşünjeli etmeli! Olaryň gözlerini açmaly! Uly diýmän, kiçi diýmän okatmaly. Mekdepleri açmaly, olarda türkmen çagalaryny türkmen dilinde okatmaly. Bu wajyp pikir — halka bilim bermek — şol döwrüň ilkinji türkmen intelligentlerinde-de bardy. Ýogsa-da Tekinskaýany ýekelikden, ýalňyzlykdan halas edenem şol intelligentler boldy. Ine, olar: Nikolaý Han Ýomudskiý, Muhammetguly Atabaýew, Gasan Efendiýew…

25',1204);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (26,1,26,'Tekinskaýa olar bilen hemişe aragatnaşykda bolýar. Tekinskaýa-da beýleki intelligentler ýaly bir esasy pikire gulluk edýär — olam agyr ýagdaýa düşen halkyny halas etmek. Ilkinji türkmen intelligentleriniň biri-birine ýazan hatlaryna üns bereliň. Nikolaý Han Ýomudskiniň Muhammetguly Atabaýewe ýasan haty: «Sen okamadyk bolsam bagtly bolardym diýip ýazýarsyň. Gyýylma, çünki aňly-düşünjeli bolup öz halkyň betbagtlygyny görmäge mümkinçilik gazanýaň. Saňa bu zatlar agyr degýändir. Ýöne beýlekilere haýyr etmäge howluk. Meniň gadyrdanym Muhammetguly! Ruhdan düşme! Biz soňuna çenli gidişmelidiris. Mert bol, gaýrat et-de seminariýaňy gutar. Soň näme etmelidigini maslahatlaşarys. Adam diýeniň haýwan ýaly ýaşaman, onuň ruhy belent bolmaly. Ine, sen häzir şeýle wajyp durmuşa gadam basýaň. Seniň pikirleriň, gaýgy-aladalaryň iň ýokary durmuş, ol ruhy baýlyk!» Gasan Efendiýewiň Muhametguly Atabaýewe ýazan hatyndan: «agyr dürmuşy ruhyçökgünlik bilen dälde, iş bilen, boş gürrüňler bilen däl-de, aýgytly hereket bilen düzedip bolar. Onuň üçin tizräk kursy tamamlap, ölüp barýan halkyň içine barmaly. Olary direldýän öz balzamyň bilen halas etmeli».

26',1148);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (27,1,27,'Tatýana Tekinskaýanyň Muhammetguly Atabaýewe ýazan hatyndan: «Meniň mähribanym, eziz dostum Muhammetguly! Şu gün meniň 30 ýaşymyň dolýan güni. Biziň ülkämiziň eýelenmegine-de 27 ýyl bolýar. Men öz ýaşlarymyza olaryň ösüp, ähli halkymyza ruhy taýdan ýokary göteriliş we azatlyk berjegine berk ynanýaryn. Elbet-de, belki sen ony görüp bilmersiň, emma seniň çagalaryň we agtyklaryň ol döwürde ýaşarlar!» Ýüzi tozanlap giden, içi hat-petekli galyň-galyň papkalary açyp, olaryň içindäki hatlara göz gezdirýäris… Ynha ýüzi «Sekretno» belgili hatlar. Olaryň biri bilen tanyş bolýarys. Türküstanyň raýon gorag bölüminiň naçalniginiň Zakaspiý oblastynyň naçalnigine iberen hatyndan: «Size habar bermegi özüme borç hasap edýärin. Tatýana Mihaýlowna Tekinskaýa, Han Ýomudskiý, şonuň bilen birlikde Gasan Efendiýew, Muhammetguly Atabaýew bilen dostluk aragatnaşygyny saklaýar. Han Ýomudskiniň täsir etmegi bilen Tekinskaýa Zakaspiý oblastynda ýaşamak bilen ruslaryň ony dogduk mekanyndan alyp gidip, onuň bütin durmuşyny zaýalandygyny aýtmak bilen häli-şindi zeýrenýär. Graf Paleniň Zakaspiý oblastynda rewiziýa geçirýän mahalynda bolsa, Tekinskaýa türkmenleri ýerli häkimiýete garşy öjükdirdi».

27',1187);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (28,1,28,'Türkmen intelligentleriniň batyrgaý hereketleri Patyşa Russiýasynyň nökerlerine ýaramaýar. Şonuň üçin olar aýgytly hereket edip başlaýarlar. 1913-nji ýylyň iýun aýynyň 28-inde M. Atabaýewiň öýi dökülýär. 126 sany hat, makala tapylýar. Şol hatlaryň içinde Tekinskaýanyň ýazan hatlary hem bar. H. Ýomudskiý, M. Atabaýew tussag edilýär. Olar pantürkizmde aýyplanýarlar. Annagül ejäniň otagynyň bir burçunda duran kiçijik stoluň üstündäki sagat «jyk-jyklap» işläp dur. Olar her sekundy, her minudy hasaplaýar. Adam durmuşynyň wagty şeýdip geçip dur. Sagadyň dili öňe gidýär, wagt welin hol yzda galýar. Ejesiniň keç ykbalyny her gezek ýatlamak 80 ýaşy arka atan ýarawsyz aýala ýeňil düşenokdy. «Şol ýyllar ejem rus çinownikleriniň gözünden sypmaýardy. Onuň her bir ädimini yzarlaýardylar. Ýogsam ejem şol kyn döwürde-de maşgala edinmäge ýetişdi. Aşgabatda ýaşaýan Annamyrat Gurbanow diýen mugallym ýigide durmuşa çykdy. Ýaşabermeli ýaly. Olaryň haý diýmän gyzlary boldy. Gülsoltan diýip at goýdular. Emma ejem arkaýyn otyranokdy. Ol öz öňünde goýan maksadyna ýetmek üçin hemme zatdan geçýärdi. Ine, ahyrsoňy onuň jezasynam berdiler. Artyk stansiýasyna sürgün etdiler. Şeýle bolansoň, kim ony

28',1191);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (29,1,29,'maşgala edip saklajak? Dargady ýene-de maşgala» Häzirki Artyk obasy täze ýerde gurlupdyr. Stansiýaň edil gapdaljygynda. Tekinskaýanyň sürgün edilen köne Artyk obasy bolsa serhede ýakyn ekeni.

IV Häzir şol gadymy oba haraba bolup ýatyr. Şol ýerlere aýlanyp görýäň welin iniň jümşildäp gidýär. Köneje jaýlar, haýatlar, käbir ýerlerde ojaklaryň ýerleri bildirip dur. Birtüýsli, seni tukatlyk gaplap alýar. Ozalky serhet zastawasy, gümrükhana, rus we ermeni täjirleriniň obalary hem haraba bolup ýatyr… Artyk stansiýasyndaky täze oba aýlanyp ýören mahalymyz bizi 85 ýaşly Öwlüýaguly aga bilen tanyş etdiler. Obanyň iň ýaşuly adamsy ekeni. Inçeden uzyn, agajet ýaşuly. Tekinskaýany öz gözleri bilen gören adam. « — Biz ol wagtlar 4-5 ýaşlarymyzdaky çagadyk. Köplenç zastawanyň ýanynda, gümrükhananyň töwereginde oýnardyk. Ine, şonda biz orta boýly, horja garaýagyz gyzy häli-şindi görerdik. Ol hemişe rus eşigindedi. Çagalary okatmak üçin ýörite mekdep açyldy. Şoňa biziň obamyzdan Orazgeldi Çekiç hem gatnardy. Ol şol mugallyma aýalyň ýanyndan

29',1044);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (30,1,30,'aýrylmaýardy. Soň Orazgeldi şol aýala öýlendi. Oba adamlary «Orazgeldi öz mugallymyna öýlenäýipdir» diýip, geň galypdylar». Artykdaky dünýewi mekdep häzir Artykgül Tekinskýanyň adyny göterýär. Ol ýerde Tekinskaýanyň ömrüne bagyşlanan kiçiräk muzeýem bar. Gapydan giräýen ýeriňde bolsa Tekinskaýanyň uly portreti dur… Mekdebiň taryh mugallymy bilen gürrüňdeş bolanymyzda ol şeýle gürrüň berdi: «1968-nji ýylda biz mugallymlar bolup öz mekdebimize Artykgül Tekinskaýanyň adyny dakmagy makul bildik. Emma şol wagt bize garşy çykdylar. Aşgabatdan bize şeýle mazmunly hat geldi: «Artykgül Tekinskaýa Patyşa Russiýasynda terbiýe alan adam. Onuň terjimehaly doly öwrenilýänçä onuň adyny mekdebe dakmaly däl». Biz Artykgül Tekinskaýanyň adyny diňe 1991-nji ýylda, Garaşsyzlygy alanymyzdan soň mekdebe dakmaly bolduk. Diňe şonda rugsat berdiler». Annagül eje Orazgeldi Çekiç oglunyň suratyny synlap oturyşyna gürrüň berýär: «Ejemiň elinde okan Orazgeldi Çekiç meň kakam bolmaly. Men 1913-nji ýylda Artykda dünýä

30',1006);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (31,1,31,'inipdirin. Orazgeldi ozal demirýol işgäri ekeni. Soň ol gümrükhana koçegar, hojalykçy bolup işe geçýär. Ol wagtlar serhede ýakyn uly gümrükhana bar ekeni. Ejem şol ýerde dilmaç bolup işläpdir. Haçan-da ejem öz serişdesine mekdep açanda, Orazgeldi onuň ýanyna işe geçipdir. Mekdebe garawullyk edipdir. Ejemiň elindede okapdyr. Kakamyň ozal bilimi ýok ekeni. Ine, onsoň 25 ýaşda partaň başyna geçmeli bolupdyr. Onuň ejemiň elinde alan bilimi, soň ol hiç ýerde okamandyr. Kakam owadan, syratly adam bolupdyr. Ejeme duşanyndan ol üýtgeşik geýinmäni çykarypdyr. Medeniýetlije, arassaja geýinipdir. Kakamyňam asly Gökdepeden ekeni. Ruslar Gökdepä çozanda, bosgunlaryň bir bölegi Artyk obasynda mekan tutunypdyr. Ejem öz mekdebinde ýönekeý adamlaryň çagalaryna başlangyç bilim berýärdi. Rus, türkmen, ähli çagalary okadýardy. Uzakdan gatnaýan çagalar üçin ol ýatakhana-da döredipdir. Ejemi halk üçin edýän aladalary üçin Artykda gowy görüpdirler. Oňa ýerli halk «Artykgül» diýip at goýupdyr. Emma, ejemiň halk arasyndaky abraýy rus çinowniklerini alada goýupdyr. Olar dürli bahanalar bilen ejeme azar beripdirler». Tatýana Tekinskaýanyň Artykda işlän döwürleri onuň üstünden köp arzalar ýazylypdyr. Şolaryň ählisinde-de

31',1216);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (32,1,32,'çinownikler bu batyrgaý zenany isledigiçe garalapdyrlar. Ine, şeýle hatlaryň biri. Ol Türkmenistanyň merkezi arhiwinde saklanylýar. Ol 1913-nji ýylda Etek pristawy, kapitan Grudzinskiniň adyndan Aşgabadyň gözleg punktunyň müdirine iberilipdir. Hatyň ýüzünde «Sekretno» diýlen belgi bar: «Türkmenleriň «Artygyň güli» diýip atlandyrýan Tekinskaýa mugallymy Artykly türkmen Orazgeldi Çekiç ogly bilen ýaşaşýar. Ondan Tekinskaýanyň bir çagasy bar. Ol şu ýyl tomus dünýä indi. Orazgeldi mekdepde garawul bolýar. Özem juda gödeksi. Artykly türkmenler Tekinskaýanyň öýüne az barýarlar. Mugallyma käbir adamlara hat işini düzedip berýär. Ol hiç kimiň öýüne baranok. Ruslardan onuň ýanyna hiç kim baranok. Umuman, ýerli halka känbir ýarap duranok. Senatoryň rewiziýa geçýän mahaly bolsa Tekinskaýa ýerli häkimiýete garşy halky öjükdirdi…» Annagül eje pikire batyp oturyşyna gaýgyly bir pursaty ýatlaýar: « — Patyşa Russiýasynyň çinownikleri ejemden dynmagyň aladasyny edip başladylar. Ilki kakamy tussag etdiler. Soňam ejemi iki çagasy — men hem Gülsoltan bilen Uzak Ukraina sürgün etdiler. Bu 1914-

32',1094);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (33,1,33,'nji ýylda bolupdy. Ukrainada bolsa ejem tä 1924-nji ýyla çenli bolup, dowzahdanam beter agyr durmuşy başdan geçirdi». Artykgül Tekinskaýanyň Kiýewde gyzlary Annagül hem Gülsoltan bilen bile düşen suratlary bar. Onda Tekinskaýa gartaşypdyr. Saçlary çal, hortaň. Ýöne gözleri welin birjik-de üýtgemändir — namysjaň gözler. Agyr durmuş ony birjik-de boýun egdirip bilmändir. Ol gartaşanam bolsa, entek gaýduwsyzdy, gujurlydy. Suratda ol gyzlary bilen Kiýewiň wokzalynda dur. Gyzlaram, özem ýewropa eşiginde. Artykgül Tekinskaýa Ukraina baranyndan ýerli poliseýskileriň göz astynda işlemeli bolýar. Eýýäm 1915-nji ýylda Kiýewiň gubernatory Zakaspiý oblastynyň naçalnigine hat ýollap, ondan Tatýana Tekinskaýanyň geçmişi, onuň ahlak häsiýetleri, syýasy garaýyşlary barada maglumatlary ýollamagy haýyş edýär. Zakaspiý oblastyndan bolsa Tekinskaýany diňe garalap biljek maglumatlar iberilýär. Onuň erkin pikirlidigini, hemişe häkimlere garşydygyny, oňşuksyzdygyny Kiýewiň gubernatoryna habar berýärler. Şeýlelikde, Tekinskaýa Urainada-da hemişe göz astyna alnyp, ol jemgyýet üçin howply hasap edilýär. Ukrainadada Artykgül Tekinskaýa mugallymçylyk işini dowam

33',1156);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (34,1,34,'etdirýär. Başda Ositýanýažka diýen obada iki klasly uçilişede okadypdyr. Soňra Çigrin uýezdiniň iki ýyllyk Iwangorod uçilişesinde, iň soňundanam Çerkasskiý okrugynyň Kamenka diýen ýerinde çagalara bilim beripdir. Baran ýerinde-de özüniň adamkärçiligi bilen özüni aldyrypdyr. Ýerli adamlar bu garaýagyz, akylly aýala uly hormat goýupdyrlar. Nähili kynçylygam bolsa, Artykgül Tekinskaýa mertlerçe çekipdir. Annagül eje şol agyr günler barada kynlyk bilen ýatlaýar. « — Kynçylyklary görmek ejemiň maňlaýyna ýazylypdyr. Görgüliň gören güni ýok. Emma şondada öz diýeninden çykanok.Ol ähli ýerde-de adalatlylyk isleýärdi. Adalatlylyk — onuň başynyň täji. Biz Ukraina baranymyzda I jahan urşy başlandy. Dünýäni apy-tupan tutdy. Biziň görmedik günümiz bolmaly. Açlygam, horlugam, zorlugam başdan geçirdik. Ýöne ejem gaýrat etdi. Hemme kynçylyklara garşy mertlerçe göreşdi. Kakam Orazgeldem biz bilen ep-esli wagt ýaşady. Ýöne ony soň gyssagly Türkmenistana çagyrdylar. Bilmedik näme üçindigini, ýöne kakam gitmeli boldy… Soň kakamy biz görüp bilmedik. Sebäbi, 1917-nji ýylda rewolýusiýa başlandy, garaz, dünýäni ahyrzaman alanyna döndi. Aragatnaşyklar kesildi. Gatnawlar gutardy. Hemme zat garpyşdy. Şeýdibem kakam yzyna dolanyp

34',1224);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (35,1,35,'bilmedi. Bizem ýangynly Ukrainada bolmagymyzy dowam etdiriberdik. Şol başagaýlykda-da biziň ogul jigimiz boldy. Ýarmuhammet diýip oňa at goýduk. Garaz, keç ykbal bizi kowalaýar, bizem ondan gaçýas. Ýöne ondan gaçyp sypma ýok ekeni… Daş-töweregimiz uruş… Köçelerde ölen adamlar ýatyr. Biz bolsa çagada, oýnap ýörüs. Nahili elhençlik. Gyzyllarmy, akgwardiýaçylarmy düşer ýaly däl, şol üstümize dökülip durlar. Olaryň ählisem hyrsyz, seresap bolmasaň, duran ýeriňde janyňy jähenneme iberjekler. Adam sypatly Ezraýyllar-da. Ýadyma düşýär, bir gezek graždan urşy döwri öýümize denikinçiler döküldiler. Biziň hemmämiz garaja bolamyzsoň, jöhitdir öýdüp atjak boldular. Jöhütleri atýardylar şonda. Bizi südürdikledip goňşularymyzyň jaýyna alyp gitdiler. Ol ýerde Arseniý daýy bilen Fýokla daýza ýaşaýardy. Bizi diwaryň öňüne getirip, hatara edip goýdular. Men, Gülsoltan, ejem, ejemiň gujagynda-da bäbejik Ýarmuhammet. Soldatlar hatara düzülip bize tüpeň çenäp başladylar. Ine, birdenem serhoş ofiser buýruk berjek bolup durka, onuň ýokarda, açyk üçekde somalyp duran bir zada gözi düşäýýär. Ýokardaky zat grammofon ekeni. Ynha ýaňkylar ony alyp aşak düşürýärler. Grammofonda plastinka goýup, aýtdyryp başlaýarlar. Aýdyma-saza

35',1222);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (36,1,36,'gyzygyp, olar şobada bizi ýatdan çykardylar… Fýokla daýza bolsa ýagdaýdan peýdalanyp, bizi bildirtmän alyp gidip öz jaýyna eltdi. Soňam penjireden çykaryp, howludaky köneje sandyga salyp gizledi. Şeýdip biz halas bolduk… Ertesi gün obanyň ruhanysy Wasiliý gelip ejeme käýeýär: «Tatýana Mihaýlowna, beýle-de bir yrym etmek bormy? Hristianlaryň hajyny hökman asgyn. Şeýtseňiz hiç kim size zat diýmez… Ejem şondan soň hajy asyp goýdy. Şondan soň bize azar beren bolmady. Öýdäki hajy görüp: «Äh-ä, bular-a öz hristianlarymyz ekeni» diýip, yzyna dolanýardylar. Ejem her niçigem bolsa özüni hakyky musulman hasap edýärdi. Öýde hiç haçan hajy asmandy. Ýogsam, ol hristian dinini kabul edipdi ahyryn. Soňky gezek biziň üstümize howp abanandan soň, ejem ikonany asmaga mejbur boldy...» Annagül eje Tatýana Tekinskaýanyň gartaşan döwründäki suratyna syn edip oturyşyna gürrüňini dowam etdirdi. « — Ejem ömrüni öz dodguk mekanyny küýsäp geçdi. «Wah, ölmänkäk bir Watanymyza dolanyp baraýsak» diýip, ejir çekýärdi. 1924-nji ýylda ejem Türkmenistanyň respublika bolanyny eşidip, öýe gaýdarman boldy. Şol ýyl biz — men, doganym

36',1117);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (37,1,37,'Gülsoltan, ejem dagymyz Kiýewe gelip, Türkmenistana dolanyp barmak üçin rugsat berýän haty aldyk. Haty elimize alybam eglenmän Türkmenistana ugradyk… Ejem, men, Gülsoltan, Ýarmuhammet — hemmämiz ýola düşdük. Ejem 1924-nji ýylyň dekabr aýynda Aşgabatda geçiriljek mugallymlaryň I gurultaýyna hem howlugýardy. Türkmenistana ýetmek üçin bolsa biziň münmedik ulagymyz galmady. Mal daşalýan wagonlara çenli mündük. Bir ýerde durman ýöresek bolýar diýdik. Ahyrsoňy Watana ýetsek bolýar diýdik… Ýolda ejem erbet ýarawsyzlyk tapdy. Ýolboýy içinden bir zat tutup, azar ýamanyny berip geldi. Bakuda ejemi otludan düşürip, lukmanlara seretdirjek hem boldular. Emma ejemiň özi garşy çykdy. «Çaltrak Watanyma ýeteýin…» diýip, şol özelendi durdy. Agyr halda ýene-de ýoluny dowam etdirdi. Aşgabada gelenimizde ejemiň ýagdaýy has hem erbetleşdi. Ýöremäge ýagdaýy bolmady. Wokzaldan göni demirýol keselhanasyna alyp gitdiler. Bizi bolsa ejem ýoldaşlaryndan internada tabşyrmagy haýyş etdi…

V Bizi bolsa ejem ýoldaşlaryndan internada tabşyrmagy

37',1031);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (38,1,38,'haýyş etdi… «Sag-aman keselhanadan çyksam, çagalary soň özüm ýygnaryn» diýip aýdypdyr. Bizi — meni, Gülsoltany, Ýarmuhammedi wokzaldan alyp, Ene Kulyýewa adyndaky internada eltip tabşyrdylar. Üç gün geçenden soň bize ejemiň ölendigini habar berdiler. Ejem biz bilen hoşlaşybam bilmän bu dünýäden ötdi… Ejir çekip öldi görgüli… Ol garahassalyk keseli bilen kesellän ekeni.» Annagül eje ep-esli wagt geplemän dymyp oturdy. Gürläp bilmän bogazy doldy. Soňam ýerinden galyp, penjiräniň öňüne bardy. Daşaryny synlap durdy. Men bolsa öňümde ýatan Tatýana Tekinskaýanyň suratyny elime alyp, synlap oturdym. Gaýduwsyz türkmen zenanynyň gaýratly ýüzlerine, gözlerine seredip, pikire batdym. Onuň geçen pajygaly günlerini ýadyma salyp, ep-esli wagt oturdym. Gör, nähili gaýduwsyzlyk! Bu bir hakyky halk gahrymany ahyryn! Milli gahryman! Türkmen halkynyň bagtly güni ugrunda dyngysyz göreşen türkmen zenany. Watanyny, halkyny tüýs ýürekden söýen şahsyýet. Hawa, hawa, şahsyýet… Onda-da Beýik şahsyýet! Annangül ejäniň ýuwaşjadan çykan sesi meni özüme getirdi. Ol ulydan demini aldy-da gürrüňini dowam etdirdi.

38',1102);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (39,1,39,'« — Ejem ölensoň biz — onuň çagalary, internatda galyberdik. Internat diňe gyzlaryňkydy. Oglanlar bolanokdy ol ýerde. Ýöne biziň Ýarmuhammedimiz gaty kiçijek bolansoň, ony internatda galmaly etdiler… Biz tä 1930-njy ýyla çenli internatda terbiýelendik. Soň herimiz öz durmuş ýolumyza gidiberdik. Men Baýramalydaky oba hojalyk institutynda okadym. Gülsoltan uniwersitetiň biologiýa fakultetine okuwa girdi. Ol soň uly alym bolup ýetişdi. Saglyk ýagdaýlary zerarly Gülsoltan Kryma göçüp gidip, ömrüniň ahyryna çenli şol ýerde ýaşady. Onuň ogul-gyzlary häzir Krymda ýaşaýarlar. Ýeke-täk oglan jigimiz Ýarmuhammet bolsa demirýol tehnikumynda okaýardy. Uruş başlandy-da, ony 18 ýaşynda alyp gitdiler. Ol uruşdan gaýdyp gelmän wepat boldy… Meniň kakam, Orazgeldi Çekiç bolsa soň bizi düýbünden ýatdan çykardy. Ýaşynyň soňuna çenli ol biçäre birnäçe gezek öýlenipdir. Iň soňunda-da, 1971-nji ýylda Sankt-Peterburga rus aýalyndan bolan gyzynyňka gezelenje baranda, daçada tarpa-taýyn ölüpdir… Onuň jesedini Türkmenistana getirmäge mümkinçilik bolmansoň, Orazgeldi Çekiç SanktPterburgyň gonamçylyklarynyň birinde jaýlanypdyr. Onuň mazary häzir şol ýerde… Şeýdip biz dargadyk… Diri galan diňe men. Men, Annagül Myradowna

39',1214);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (40,1,40,'Tekinskaýa. Tatýana — Artykgül Tekinskaýanyň körpe gyzy… Meni häzire çenli bir zat biynjalyk edýär. Şu wagta çenli ejemiň jaýlanan ýeri belli däl. Onuň mazarynyň nirededigi belli däl. Biz — onuň çagalary köp gyzyklandyk bu mesele boýunça, ýöne hiç ýerdenem belli bir jogap almadyk. Meniň bolsa bilesim gelýär onuň mazarynyň nirededigini. Ölmänkäm görsem diýýän…» Türkmenistanyň merkezi döwlet arhiwinde işläp ýören wagtym bir kiçiräjik maglumatyň üstünden bardym. Maşinkada çap edilip goýlan bir sahypa kagyzyň ýüzünde şeýle ýazgylar bardy: «Ilkinji pedagoglaryň biri, Merýem Ezizowna Kerbabaýewnanyň ýatlamasyndan: «1924-nji ýylyň dekabr aýynda Aşgabadyň Magaryf öýünde Türkmenistanyň mugallymlarynyň I gurultaýy işläp durdy. Birinji çykyşdan soň münbere Muhammet Geldiýew çykdy. Ol zalda oturan mugallymlara ýüzlenip şeýle diýdi: «Öz dogduk mekanyna dolanyp gelýärkä, ýolda ilkinji türkmen mugallymy Tatýana Tekinskaýa agyr derde uçrady. Ol öz Watanynyň gülläp ösýänini görüp bilmän demirýol keselhanasynda ýogaldy. Tekinskaýa bütin ömrüni öz halkynyň bagtly durmuşy üçin göreşip gelipdi. Artykgül Tekinskaýanyň ýagty ýadygärligine baş egip, bir minut ýeriňizden

40',1168);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (41,1,41,'turmagyňyzy haýyş edýärin». Biz ähli mugallymlar bolup demirýol keselhanasyna bardyk. Tatýana Tekinskaýa bilen ömürlik hoşlaşdyk… Ony musulman gonamçylygyna äkidip jaýladylar…» Bu haty okanymdan soň wajyp bir pikir meni biynjalyk etdi. Tatýana — Artykgül Tekinskaýanyň nirede jaýlanandygy anyk belli däl. Mümkin, bilýän adamlar bardyr. Ýöne, biziň ýüz tutan adamlarymyzyň-a habarlary ýok ekeni. Hatda onuň gyzy Annagül Tekinskaýanyň özem bilenok. Mümkin bilýänler bardyr... Eger şeýle bolsa, onda sesleniň, adamlar, sesleniň! Türkmeniň taryhynda öçmejek yz galdyran gaýduwsyz zenanyň hatyrasy üçin sesleniň! Tatýana Tekinskaýanyň meşhur portretini ýene bir gezek elime alýaryn. Ol merdana gyzyň gara gözleri bize seredip dur. Ine, onuň şol gözlerindenem men Tekinskaýanyň bir wagt aýdan ajaýyp sözlerini okadym: «Şu gün meniň otuz ýaşymyň dolýan güni. Biziň ülkämiziň eýelenmegine-de 27 ýyl bolýar… Men öz ýaşlarymyza olaryň ösüp, ähli halkymyza ruhy taýdan ýokary göteriliş we azatlyk berjegine berk ynanýaryn. Elbetde, belki sen ony görüp bilmersiň. Emma, seniň çagalaryň, agtyklaryň ol döwürde ýaşarlar!»

41',1111);
INSERT INTO `pages` (`id`,`document_id`,`page_number`,`text`,`character_count`) VALUES (42,1,42,'*** Häzir Tekinskaýalardan aýatda diri galany ýok. 85 ýaşan Annagül eje-de pahyr boldy. Emma, olar baradaky ýatlama welin ömürlik galdy... Türkmen halkynyň merdana gyzy, halkymyzyň bagtly günleri ugrunda janyny gaýgyrmadyk gaýduwsyz zenan Tatýana Tekinskaýanyň tüýs ýüreginden beslän arzuwy 1991-nji ýylyň oktýabr aýynyň 27-sinde hasyl boldy. Türkmenistan özüniň Garaşsyz döwlet bolandygyny bütin äleme jar etdi. Türkmen halkynyň ömürbaky arzuw edip gelen maksady amala aşdy. Halkymyzyň Garaşsyzlyga gözi düşdi… Türkmenistanyň ilkinji Prezidenti Beýik Saparmyrat Türkmenbaşynyň ýolbaşçylygy astynda türkmen halky döwletimiziň Garaşsyz binýadynyň düýbüni tutdy. Ol edil ýaşajyk nahal dek ünse-idege, tükeniksiz alada mätäç… Ony ösdürip ýetişdirmek ählimiziň mukaddes borjumyz… Garaşsyzlyk her bir halk üçin bagt... Türkmen halky üçinem Garaşsyzlyk uly bagt… Ony goramaly, eý görmeli, ýüzüňe sylmaly! Ýazmyrat Şadurdyýew

42',922);
COMMIT;
SET FOREIGN_KEY_CHECKS=1;
